[package]
name = "fastwalk"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fastwalk"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
ignore = "0.4"
crossbeam = "0.8"
globset = "0.4"
